### ISSUE TITLE
How can we use it with typescript?

### ISSUE THREAD

**Issue by stgolem** [transitive-bullshit/react-modern-library-boilerplate#1]
Is there any simple way to use this boilerplate with typescript + tsx?

**Comment by transitive-bullshit** [comment]
All you need to do is add the rollup typescript plugin (see rollup [plugins](https://github.com/rollup/rollup/wiki/Plugins)) to [rollup.config.js](https://github.com/transitive-bullshit/react-modern-library-boilerplate/blob/master/rollup.config.js#L26).

Note that I'm not 100% sure which order these plugins should go in, but I would think typescript should be at the top.  If anyone else has more experience with typescript + rollup, I'd love some clarification @victorystick @ezolenko.

**Comment by stgolem** [comment]
I've done this with `rollup-plugin-typescript2`. Here is full config:

```
import babel from "rollup-plugin-babel";
import commonjs from "rollup-plugin-commonjs";
import postcss from "rollup-plugin-postcss";
import resolve from "rollup-plugin-node-resolve";
import typescript from "rollup-plugin-typescript2";

import pkg from "./package.json";

export default {
  input: "src/index.tsx",
  output: [
    {
      file: pkg.main,
      format: "cjs"
    },
    {
      file: pkg.module,
      format: "es"
    }
  ],
  external: ["react", "react-dom", "prop-types"],
  plugins: [
    typescript(),
    resolve(),
    commonjs(),
    postcss({}),
    babel({
      exclude: "node_modules/**"
    })
  ]
};
```

But with this i had to configure **tsconfig.json** with `"allowJs": false`

**Comment by transitive-bullshit** [comment]
Awesome -- thanks, @stgolem. I'll add this info to the readme.

**Comment by transitive-bullshit** [comment]
I'm publishing a Medium article on this and will link to this issue there.  Thanks everyone!

**Comment by isha-bansal0115** [comment]
@transitive-bullshit: did you publish a medium article for this?
