### ISSUE TITLE
Document how to create named exports

### ISSUE THREAD

**Issue by jvorcak** [transitive-bullshit/react-modern-library-boilerplate#11]
Hi,

First of all, thank you for this repository. It's a great starting point for writing React packages and I love the CRA integration!

However, could you please document how can one define named exports using this setup? Usually when you write a library you want to export multiple things and it would really help everyone to get started faster. Ideally you could provide an example as well -> what is the best practice in your opinion? 

Thanks

**Comment by transitive-bullshit** [comment]
Great call -- I've recently had to do this for a module myself.

How does this [branch](https://github.com/transitive-bullshit/react-modern-library-boilerplate/tree/feature/multiple-exports) look to you?  It exports two components, `Foo` and `Bar`, and shows how to use them from the example app.

If it looks solid, I'll add a note to the readme pointing to this branch as an example.

Thanks!

**Comment by jvorcak** [comment]
@transitive-bullshit great, but I'd also keep the example of a default export.
So instead of 
`import { Foo, Bar } from 'react-modern-library-boilerplate'`

It'd be nice to have
`import Foo, { Bar } from 'react-modern-library-boilerplate'`

**Comment by transitive-bullshit** [comment]
Agreed.  I tried exporting both named + default, but rollup prints a warning when you try to mix default and named exports.  I'm not sure why, as it should work when bundling for `es` and `cjs` formats.

Maybe you can get it work work properly in the `feature/multiple-exports` branch?

**Comment by transitive-bullshit** [comment]
Maybe this warning can be safely disregarded, as it appears to only affect `umd` builds ([issue](https://github.com/rollup/rollup/issues/1044)), but this is outside of my domain of experience.

**Comment by jvorcak** [comment]
@transitive-bullshit the same for me, I'm not experienced in this area at all, to be honest. Maybe it would make sense to at least document it and leave the final decision to the one who uses it?

**Comment by transitive-bullshit** [comment]
Sounds good.  Added in https://github.com/transitive-bullshit/react-modern-library-boilerplate/commit/c80ddf240b79e09845e3b0ecaf7a97eb501fea5f

**Comment by transitive-bullshit** [comment]
Fixed in https://github.com/transitive-bullshit/react-modern-library-boilerplate/commit/ae467fafd296406fc2762ddc4bc6e6cf3911c372 💯

**Comment by jvorcak** [comment]
@transitive-bullshit 👏 thanks a lot for a quick response 👍
