### ISSUE TITLE
new library automation

### ISSUE THREAD

**Issue by raycohen** [transitive-bullshit/react-modern-library-boilerplate#12]
create-react-app's readme opens with
```
npx create-react-app my-app
cd my-app
npm start
```

It would be great if this project had a similar script to avoid needing the manual steps in the walkthrough. Smoothing out this process would probably increase adoption and participation too.

A blueprint-based interactive script could also open the door to putting more opinionated options in. For example, you could answer yes/no for a storybooks, prettier, flow, sass etc. I'm assuming adding those things directly to the project as is now would be too opinionated.

I'm curious about your thoughts on roadmap in general.

**Comment by transitive-bullshit** [comment]
I definitely agree that a cli would be a great next step and that it would significantly increase adoption.

I'd love to work on this when I get some spare time; otherwise, feel free to implement your own CLI and we can link the projects together.

Let's track progress on this issue.

**Comment by transitive-bullshit** [comment]
I just published a new CLI for this boilerplate:  [create-react-library](https://github.com/transitive-bullshit/create-react-library).

Please check it out and provide feedback 👍

**Comment by raycohen** [comment]
Awesome! I tried installing with `npm install -g` but I'm not getting the executable in my path.

I think adding a `bin` section to the package.json might fix this https://docs.npmjs.com/files/package.json#bin

Right now running `ls -al $(npm -g bin)` shows me symlinks for all the other executables I have globally installed, but I'm not getting `react-modern-library-cli` in that list like I'd expect

**Comment by transitive-bullshit** [comment]
Good call; I definitely forgot to add that.

Updated version should work now.  Thanks!

**Comment by raycohen** [comment]
Yeah, looks good now!

**Comment by transitive-bullshit** [comment]
Fixed some issues with installation and added some visuals.  Let's track future issues in that repo.

Thanks!
