### ISSUE TITLE
Use with a script Tag

### ISSUE THREAD

**Issue by khpatel4991** [transitive-bullshit/react-modern-library-boilerplate#18]
Hi,

I'm building a library with react and draftjs, which needs to be injectable in any html page and then instantiating the component on demand through a simple function that should be available in global namespace. 
```
<script src="https://mycdn.com/MyAwesomeLib.min.js"></script>
<script>loadMyLib(validHtmlElement, initialProps)</script>
```

**Comment by transitive-bullshit** [comment]
You want to tell rollup to output a `umd` bundle as well.  Change `rollup.config.js`to look like this:

```js
import babel from 'rollup-plugin-babel'
import commonjs from 'rollup-plugin-commonjs'
import external from 'rollup-plugin-peer-deps-external'
import postcss from 'rollup-plugin-postcss'
import resolve from 'rollup-plugin-node-resolve'
import url from 'rollup-plugin-url'

import pkg from './package.json'

export default {
  input: 'src/index.js',
  output: [
    {
      file: pkg.main,
      format: 'cjs',
      sourcemap: true
    },
    {
      file: pkg.module,
      format: 'es',
      sourcemap: true
    },
    {
      file: 'dist/umd.js',
      format: 'umd',
      sourcemap: true
    }
  ],
  plugins: [
    external(),
    postcss({
      modules: true
    }),
    url(),
    babel({
      exclude: 'node_modules/**'
    }),
    resolve(),
    commonjs()
  ]
}
```

**Comment by khpatel4991** [comment]
I do have that, but it says missing global variable names. And when I use that script in a normal html page, it says React not defined. Is there a way I can bundle react's production minified build and draftjs minified build in my script? Or user has to add those scripts independently before my component script loads?

**Comment by khpatel4991** [comment]
Hey there,
I was successfully able to get it to work on my library. I added `react`, `react-dom` and `draft-js` as `dependencies` rather than `peer-dependencies` which was kind of stupid on my part as my goal was to get all of them bundled together. Also, In UMD build for rollup, `name` is compulsory option. But thanks for the help. Actually, I started the library with your original blog post on medium for creating baller react libs and the project kinda evolved from there. However the only caveat is, I have two rollup config, one for UMD build that exports a function to load the editor, while another for `cjs` for direct use with react or with npm as a plain component. The following was my final rollup build for UMD.

```
  {
    input: "src/index.js",
    output: [
      {
        file: pkg.browser,
        name: "PerfectTenseEditor",
        format: "umd",
        sourcemap: true,
      }
    ],
    plugins: [
      replace({
        "process.env.NODE_ENV": JSON.stringify("production")
      }),
      external(),
      builtins(),
      postcss({
        modules: true,
      }),
      url(),
      babel({
        exclude: "node_modules/**",
        plugins: ["external-helpers"]
      }),
      resolve({
        browser: true
      }),
      commonjs({
        include: "node_modules/**",
        preferBuiltins: false,
        namedExports: { 
          "node_modules/draft-js/lib/Draft.js": [ "Editor", "EditorState", "CompositeDecorator", "SelectionState", "Modifier", "convertFromRaw", "convertToRaw" ],
          "node_modules/react/index.js": ["Component", "PureComponent", "Fragment", "Children", "createContext"],
        },
      }),
      progress({
        clearLine: false,
      }),
      terser(),
    ],
    external: ["utf-8-validate", "bufferutil"]
  }
```
