### ISSUE TITLE
Does not work with yarn

### ISSUE THREAD

**Issue by jptissot** [transitive-bullshit/react-modern-library-boilerplate#2]
If you use yarn instead of NPM to install packages, you get an error in the console. I also tried removing the package-lock.json and then doing an npm install and it also failed with the same error 

`[!] (commonjs plugin) SyntaxError: Unexpected token (11:19) in \src\index.js
src\index.js (11:19)
SyntaxError: Unexpected token (11:19) in \src\index.js
    at error (\node_modules\rollup\dist\rollup.js:185:14)
    at Promise.resolve.then.catch.err (\node_modules\rollup\dist\rollup.js:9448:6)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3`

**Comment by transitive-bullshit** [comment]
Thanks for the bug report, @jptissot!

I just pushed a fix and tested everything with both `npm` and `yarn`.  Please let me know if the latest version fixes your issue.

**Comment by jptissot** [comment]
Thanks will test this today. Just by curiosity which os and versions of npm / yarn are you using? I used node 8.9 and yarn 1.3.1

**Comment by transitive-bullshit** [comment]
Mac OS Sierra, Node v8.8.0, and Yarn v1.3.2

There was a legitimate issue with the ordering of rollup plugins that I fixed, and I'm not sure why it worked previously with npm.

**Comment by transitive-bullshit** [comment]
Closing for now; please let me know if you experience any issues with yarn and I'll reopen.
