### ISSUE TITLE
Import images

### ISSUE THREAD

**Issue by Ciaran0** [transitive-bullshit/react-modern-library-boilerplate#22]
Hi,

I have a component that imports images, how do i get these bundled with the component at build time?

Thanks,
Ciaran

**Comment by Ciaran0** [comment]
Can be done with
https://github.com/rollup/rollup-plugin-image

I might throw it in the docs

**Comment by transitive-bullshit** [comment]
Also see https://github.com/transitive-bullshit/create-react-library/issues/46 which doesn't require you to install an extra package. `rollup-plugin-image` is great and also works 😄

**Comment by Ciaran0** [comment]
@transitive-bullshit Ah great thanks, dunno how I missed that!
