### ISSUE TITLE
Crazy preferBuiltins stuff

### ISSUE THREAD

**Issue by fix-me** [transitive-bullshit/react-modern-library-boilerplate#23]
Hi,

at first I would like to thank you for this beautiful package compilation!

Nevertheless I have some troubles and a single line of code breaks everything.
I want to import Swagger from 'swagger-client' package which makes me crazy.

So I simply added it through `npm i swagger-client` and inserted `import Swagger from 'swagger-client';` in the library **'src/index.js'**. `npm start` and baam, broken.

Do you have any suggestion? What am I missing?

Thank you very much for investigation!

**Comment by transitive-bullshit** [comment]
Closing this in favor of the duplicate issue in CRL.
