### ISSUE TITLE
build fails after adding a css style

### ISSUE THREAD

**Issue by tarcon** [transitive-bullshit/react-modern-library-boilerplate#3]
Adding any style to src/styles.css leads to a syntax error during build.
[!] (babel plugin) SyntaxError: /Users/.../react-modern-library-boilerplate/src/styles.css: Unexpected token (1:0)

**Comment by transitive-bullshit** [comment]
Good catch! This was an issue which crept in around ordering of rollup plugins which I just pushed a fix for in v1.0.6.

Please let me know if this fixes your error.

**Comment by transitive-bullshit** [comment]
Closing for now; please let me know if you're still experiencing issues.  Thanks!
