### ISSUE TITLE
Missing Babel-Eslint plugin

### ISSUE THREAD

**Issue by mcabs3** [transitive-bullshit/react-modern-library-boilerplate#5]
Looks like your .eslintrc is looking for `babel-eslint` but it isn't in your package.json.

BTW, this library looks awesome! nice work and thank you for making my life easier

**Comment by transitive-bullshit** [comment]
Good call -- just added babel-eslint to dev deps and published `v1.0.9`.

Thanks for the report and the shout out 💯

**Comment by mcabs3** [comment]
Sweet deal, if you ever need additional help, feel free to reach out. I already deployed a few modules from this!
