### ISSUE TITLE
Does .npmignore serve any purpose here

### ISSUE THREAD

**Issue by janeklb** [transitive-bullshit/react-modern-library-boilerplate#9]
Given that there's a `files` defined in `package.json`, it _seems_ like `.npmignore` is not necessary / a bit misleading. A few of the paths listed lend to some confusion: eg. `coverage/`, `scripts/`, and `test/` do not exist in the project tree.

Does this file serve any immediate purpose?

**Comment by transitive-bullshit** [comment]
Doesn't serve any purpose that I'm aware of -- just boilerplate copied over from other projects.  Feel free to ignore / remove and/or submit a PR to remove.

Thanks!

**Comment by transitive-bullshit** [comment]
Also please ⭐️ to show your love :)
